/**
 * Datasets - Search
 */
export const SET_SEARCH_DATASETS_SUCCESS = 'datasets/SET_SEARCH_DATASETS_SUCCESS';
export const SET_SEARCH_DATASETS_ERROR = 'datasets/SET_SEARCH_DATASETS_ERROR';
export const SET_SEARCH_DATASETS_LOADING = 'datasets/SET_SEARCH_DATASETS_LOADING';
export const SET_SEARCH_DATASETS_QUERY = 'datasets/SET_SEARCH_DATASETS_QUERY';
export const SET_SEARCH_DATASETS_FILTERS = 'datasets/SET_SEARCH_DATASETS_FILTERS';
/**
 * Datasets - Featured
 */
export const SET_FEATURED_DATASETS_SUCCESS = 'datasets/SET_FEATURED_DATASETS_SUCCESS';
export const SET_FEATURED_DATASETS_ERROR = 'datasets/SET_FEATURED_DATASETS_ERROR';
export const SET_FEATURED_DATASETS_LOADING = 'datasets/SET_FEATURED_DATASETS_LOADING';
/**
 * Selected Dataset
 */
export const SET_SELECTED_DATASET_SUCCESS = 'datasets/SET_SELECTED_DATASET_SUCCESS';
export const SET_SELECTED_DATASET_ERROR = 'datasets/SET_SELECTED_DATASET_ERROR';
export const SET_SELECTED_DATASET_LOADING = 'datasets/SET_SELECTED_DATASET_LOADING';
/**
 * Recent Datasets
 */
export const ADD_RECENT_DATASETS = 'datasets/ADD_RECENT_DATASETS';

/**
 * Modal - Console Modal
 */
export const SET_MODAL = 'modal/SET_MODAL';

/**
 * Modal - Console Modal
 */
export const SET_TOKEN = 'modal/SET_TOKEN';

/**
 * Carto layer
 */
export const SET_CARTO_LAYER_SLUG_SUCCESS = 'layers/SET_CARTO_LAYER_SLUG_SUCCESS';
export const SET_CARTO_LAYER_SUCCESS = 'layers/SET_CARTO_LAYER_SUCCESS';
export const SET_CARTO_LAYER_ERROR = 'layers/SET_CARTO_LAYER_ERROR';
export const SET_CARTO_LAYER_LOADING = 'layers/SET_CARTO_LAYER_LOADING';
export const SET_CARTO_MARKERS_LAYER_SUCCESS = 'layers/SET_CARTO_MARKERS_LAYER_SUCCESS';
export const SET_CARTO_MARKERS_LAYER_ERROR = 'layers/SET_CARTO_MARKERS_LAYER_ERROR';
export const SET_CARTO_MARKERS_LAYER_LOADING = 'layers/SET_CARTO_MARKERS_LAYER_LOADING';
export const SET_CARTO_CLUSTER_LAYER_SUCCESS = 'layers/SET_CARTO_CLUSTER_LAYER_SUCCESS';
export const SET_CARTO_CLUSTER_LAYER_ERROR = 'layers/SET_CARTO_CLUSTER_LAYER_ERROR';
export const SET_CARTO_CLUSTER_LAYER_LOADING = 'layers/SET_CARTO_CLUSTER_LAYER_LOADING';
export const RESET_CARTO_LAYER_OPTIONS = 'layers/RESET_CARTO_LAYER_OPTIONS';

/**
 * Water risk layers
 */
export const SET_WATER_LAYER_SUCCESS = 'water-layers/SET_LAYER_SUCCESS';
export const SET_WATER_LAYER_ERROR = 'water-layers/SET_LAYER_ERROR';
export const SET_WATER_LAYER_LOADING = 'water-layers/SET_LAYER_LOADING';
export const SET_WATER_LAYERS_ACTIVE = 'water-layers/SET_WATER_LAYERS_ACTIVE';

/**
 * Water risk basins
 */
export const SET_BASINS_SUCCESS = 'water-layers/SET_BASINS_SUCCESS';
export const SET_BASINS_ERROR = 'water-layers/SET_BASINS_ERROR';
export const SET_BASINS_LOADING = 'water-layers/SET_BASINS_LOADING';

/**
 * Twitter slider
 */
export const SET_TWITTER_SLIDES_SUCCESS = 'twitter/SET_TWITTER_SLIDES_SUCCESS';
export const SET_TWITTER_SLIDES_ERROR = 'twitter/SET_TWITTER_SLIDES_ERROR';
export const SET_TWITTER_SLIDES_LOADING = 'twitter/SET_TWITTER_SLIDES_LOADING';

