/**
 * Datasets - Search
 */
export const SET_SEARCH_DATASETS_SUCCESS = 'datasets/SET_SEARCH_DATASETS_SUCCESS';
export const SET_SEARCH_DATASETS_ERROR = 'datasets/SET_SEARCH_DATASETS_ERROR';
export const SET_SEARCH_DATASETS_LOADING = 'datasets/SET_SEARCH_DATASETS_LOADING';
export const SET_SEARCH_DATASETS_QUERY = 'datasets/SET_SEARCH_DATASETS_QUERY';
export const SET_SEARCH_DATASETS_FILTERS = 'datasets/SET_SEARCH_DATASETS_FILTERS';
/**
 * Datasets - Featured
 */
export const SET_FEATURED_DATASETS_SUCCESS = 'datasets/SET_FEATURED_DATASETS_SUCCESS';
export const SET_FEATURED_DATASETS_ERROR = 'datasets/SET_FEATURED_DATASETS_ERROR';
export const SET_FEATURED_DATASETS_LOADING = 'datasets/SET_FEATURED_DATASETS_LOADING';
/**
 * Selected Dataset
 */
export const SET_SELECTED_DATASET_SUCCESS = 'datasets/SET_SELECTED_DATASET_SUCCESS';
export const SET_SELECTED_DATASET_ERROR = 'datasets/SET_SELECTED_DATASET_ERROR';
export const SET_SELECTED_DATASET_LOADING = 'datasets/SET_SELECTED_DATASET_LOADING';
/**
 * Recent Datasets
 */
export const ADD_RECENT_DATASETS = 'datasets/ADD_RECENT_DATASETS';

/**
 * Modal - Console Modal
 */
export const SET_CONSOLE_MODAL = 'modal/SET_CONSOLE_MODAL';
/**
 * Carto layer
 */
export const SET_CARTO_LAYER_SUCCESS = 'layers/SET_CARTO_LAYER_SUCCESS';
export const SET_CARTO_LAYER_ERROR = 'layers/SET_CARTO_LAYER_ERROR';
export const SET_CARTO_LAYER_LOADING = 'layers/SET_CARTO_LAYER_LOADING';
